services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=springbootDb'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'

  libretranslate:
    image: 'libretranslate/libretranslate:latest'
    command: '--load-only en,sv'
    ports:
      - '5000:5000'
